services:
  frontend:
    container_name: mern_frontend_container
    build: ./frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mern-network
    restart: unless-stopped
    stdin_open: true
    tty: true

  backend:
    container_name: mern_backend_container
    build: ./backend
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - NODE_ENV=${NODE_ENV}
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mern-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: mern_mongo_data_container
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE}
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    command: mongod --auth
    networks:
      - mern-network
    restart: unless-stopped

networks:
  mern-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local