
services:
  frontend:
    image: lalbudha47/mern-frontend:v2.0.0
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  backend:
    image: lalbudha47/mern-backend:v2.0.0
    ports:
      - "5000:5000"
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/mern-library
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always

volumes:
  mongodb_data: