apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: bW9uZ29fdXNlcg==
  MONGO_INITDB_ROOT_PASSWORD: bW9uZ29fcGFzc3dvcmQ=
  MONGO_INITDB_DATABASE: bGlicmFyeQ==
  MONGODB_URI: bW9uZ29kYjovL21vbmdvX3VzZXI6bW9uZ29fcGFzc3dvcmRAbW9uZ28tc2VydmljZToyNzAxNy9saWJyYXJ5P2F1dGhTb3VyY2U9YWRtaW4=