# backend-config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  PORT: "5000"
  FRONTEND_PORT: "3000"
  NODE_ENV: "production"
  CORS_ORIGINS: "http://mern.example.com:8080,http://localhost:3000,http://localhost:8080"